In [3]:
import numpy as np

A = np.array([
    [1,2,3,4],
    [2,4,6,8]
]
)

print(A)
print(A.shape)



[[1 2 3 4]
 [2 4 6 8]]
(2, 4)


In [8]:
B = np.array([
    [
        [1,2,3,4],
        [2,4,6,8]
    ],
    [
        [1,3,5,7],
        [4,8,12,16]
    ]
]
)
print(B)
print(B.shape)

findx = np.where(B == 8)
print(findx)

B.ndim

B.size

[[[ 1  2  3  4]
  [ 2  4  6  8]]

 [[ 1  3  5  7]
  [ 4  8 12 16]]]
(2, 2, 4)
(array([0, 1]), array([1, 1]), array([3, 1]))


16

In [15]:
#Tugas No. 1
import numpy as np

A = np.array([
    [10,20,30],
    [5,10,20],
    [2,4,6]
]
)
print(A)

[[10 20 30]
 [ 5 10 20]
 [ 2  4  6]]


In [16]:
#Tugas No. 2
B = np.array([
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [20,21,22],
        [23,24,25],
        [26,27,28]
    ],
    [
        [30,31,32],
        [33,34,35],
        [36,37,38]
    ]
]
)
print(B)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]


In [11]:
#Tugas No. 3
C = np.array([
    [
        ["macbook",3,25000000],
        ["asus",15,11000000],
        ["hp",6,8000000]
    ],
    [
        ["iphone",5,13000000],
        ["oppo",22,5000000],
        ["vivo",8,4000000]
    ]
]
)
print(C.ndim)
print(C.shape)

3
(2, 3, 3)


In [14]:
#Tugas No. 4
D = np.array([
        ["Raka",21,"Badung","Programmer"],
        ["Bayu",22,"Denpasar","Web Developer" ],
        ["Sri",18,"Gianyar","Android Developer"],
        ["Dimas",30,"Bangli","Data Analyst"]
]
)
print(D.ndim)
print(D.shape)
print(D.size)

2
(4, 4)
16
